---
- name: Add VLANs to device(s)
  hosts: leafs
  tasks:
    - name: Add VLAN 10
      arista.eos.eos_vlans:
        config:
          - vlan_id: 101
            name: staging
            state: active
        state: merged
